name: Example Shipshape Usage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions block with required permissions
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  run-shipshape:
    uses: ./.github/workflows/shipshape.yml
    with:
      # Optional parameters with defaults shown
      shipshape-version: 'v1.0.0-alpha.1.5.0'
      sdp-platform-rules-version: 'v1.0.3'
      table-output: 'config'
      fail-severity: 'high'
    secrets: inherit  # This is needed to pass GITHUB_TOKEN to the called workflow 