name: Example Shipshape Usage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Add permissions block with required permissions
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  run-shipshape:
    uses: ./.github/workflows/shipshape.yml
    secrets: inherit # This is needed to pass GITHUB_TOKEN to the called workflow
