name: Example Shipshape Usage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-shipshape:
    uses: ./.github/workflows/shipshape.yml
    with:
      # Optional parameters with defaults shown
      shipshape-version: 'v1.0.0-alpha.1.5.0'
      sdp-platform-rules-version: 'v1.0.1'
      table-output: 'junit'
      fail-severity: 'high'
    secrets: inherit  # This is needed to pass GITHUB_TOKEN to the called workflow 