name: shipshape

on:
  workflow_call:
    inputs:
      shipshape-version:
        description: Version of shipshape to use.
        type: string
        required: false
        default: v1.0.0-alpha.1.5.0
      sdp-platform-rules-version:
        description: Version of SDP Platform Rules to use.
        type: string
        required: false
        default: v1.0.0

# Add permissions block
permissions:
  checks: write
  contents: read
  pull-requests: write

env:
  REGISTRY: ghcr.io

jobs:
  audit:
    name: shipshape_audit
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dpc-sdp/bay/ci-builder:6.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Cached Shipshape Binary
        id: cache-shipshape
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/shipshape
          key: shipshape-${{ inputs.shipshape-version }}
          restore-keys: |
            shipshape-
      - name: Download Shipshape if not cached
        if: steps.cache-shipshape.outputs.cache-hit != 'true'
        run: |
          # Download shipshape binary
          curl -L -o /usr/local/bin/shipshape https://github.com/salsadigitalauorg/shipshape/releases/download/${{ inputs.shipshape-version }}/shipshape-$(uname -s)-$(uname -m) && \
          chmod +x /usr/local/bin/shipshape
      - name: Get Cached SDP Platform Rules
        id: cache-sdp-rules
        uses: actions/cache@v4
        with:
          path: shipshape.yml
          key: sdp-platform-rules-${{ inputs.sdp-platform-rules-version }}
          restore-keys: |
            sdp-platform-rules-
      - name: Download SDP Platform Rules if not cached
        if: steps.cache-sdp-rules.outputs.cache-hit != 'true'
        run: |
          #curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o shipshape.yml https://raw.githubusercontent.com/dpc-sdp/sdp-platform-rules/${{ inputs.sdp-platform-rules-version }}/shipshape.yml
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o shipshape.yml https://raw.githubusercontent.com/MarkCalvert/sdp-platform-rules/refs/tags/${{ inputs.sdp-platform-rules-version }}/shipshape.yml
      - name: Audit codebase
        shell: bash
        run: |
          # Run shipshape
          ls -la
          cat shipshape.yml
          shipshape run . -f shipshape.yml --debug --error-code
          # shipshape run . -f shipshape.yml --error-code --output-format junit > shipshape-results.xml
      - name: Upload audit report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: shipshape-results
          path: shipshape-results.xml
      - name: Publish junit report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: shipshape-results.xml
