name: Analyze Changes in Master

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Show event data
      run: |
        echo "Event: ${{ toJson(github.event) }}"
        echo "Compare: ${{ github.event.compare }}"
        for commit in ${{ github.event.commits }}; do
            echo "Commit:${{ toJson($commit) }}"
            # For each commit, get the list of modified files from the modified property which is an array of
            for file in $commit.modified; do
                echo "File: ${{ toJSON($file) }}"
            done
        done
    
    - name: Get list of changed files
      env:
        GITHUB_SHA_BEFORE: ${{ github.event.before }}
        GITHUB_SHA_AFTER: ${{ github.sha }}
      run: |
        git diff --name-only $GITHUB_SHA_BEFORE $GITHUB_SHA_BEFORE
