name: Analyze Changes in Master

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Show event data
      run: |
        echo "Event: "${{ github.event }}"
        echo "Compare: "${{ github.event.compare }}"
        echo "Commits: "${{ github.event.commits }}"
    
    - name: Get list of changed files
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
        cat changed_files.txt

    - name: Analyze changed files
      run: |
        # Your analysis script here
        while read file; do
            echo "Analyzing $file"
            # Your analysis commands here
        done < changed_files.txt
