name: Analyze Changes in Master

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Show event data
      env:
        COMMITS: ${{ toJson(github.event.commits) }}
      run: |
        echo "Event: ${{ toJson(github.event) }}"
        echo "Compare: ${{ github.event.compare }}"
        echo "Commits: $COMMITS"
    
    - name: Get list of changed files
      env:
        GITHUB_SHA_BEFORE: ${{ github.event.before }}
        GITHUB_SHA_AFTER: ${{ github.sha }}
      run: |
        git diff --name-only $GITHUB_SHA_BEFORE $GITHUB_SHA_AFTER
